TEST_INPUT = "AxBCDDCAxD"

INPUT = "CxBCACDxBxADCAAACDADACADxDxCAxCAACDCxCAxAxDBADCABABABABxCBCBAADDDxxBAxAxBCDBBDACBBDAAAAADxCCAABCxxCBCADDDDBCBDCDCDADBDDDCCDCBBDABADDxDxCBBAAxCCBBAABAABCxACADBADDBDADBxBDxCDCCDCCADBBABABCxDDCxCDDAABABCAACAxCAABxAADCxBCBCCABCxDACBxCDxCAACCDCCCADCxCCDCDDxABDCBAADACDAxDCBDCCDDxBBxBDCACCCDBDABADxDABxBABABAABCDCCCxACADCCCBBxCACDDAADDAACBxBDCDADCxBCCCDCAAAAADxBDABACDAxAADAAAABAxADDCBDBCDxAxAACDCxABxCCACDBAACACACCBCDCBDBxAAABCCCxDBAxCBxBDDCDxADACCxCDCxACAxxBBCCBCDCDCCCBDDCABABDAACDAxACDBDCBDxDDxDABDBBBCADCDADCBDBCBABxDCBxAAACCBCAxADCBBAACCDxDDCCCAAACAABxABABABBBDxDABBDxxxDDDBABDDBBADCBBCBDCCDBCCBABxAAxBDDxCCBABxCxxABDAAxDADBADBADBBACDBDDADCAAxACCADCDBABCDCDCBDADBDCCAAxBCDxDACCBDACxxxCCDABBADACDABDCBDAxCACAACDDDBCCCACBDxBxBDBCABCxADBBACCCCAABDxACBCAABxDCDDBBBABBBDxADADBCBAxCBCxCABDDBBCDAAADDCDCBCAxBCDCDAACAxACCAADBADAABDABxACDDCxACxDDCDDAxBDAACxDCBBABBxDxBCBBDACCDxCDACDBBDxCCBCDACDCBCCBDxDADCDACDCAxCBAABADxAxADABxDCDDDBDBDCBBxCBDBDDBDxCAAAxCCABBCADDBCDDDBCCBCxBDDAAABCBCDCDAADDBxBDDCxxDCCDADDxDDADxABxBCxCABDAxBDDBBCAACADDADxACBADxAxxAADBACxBxADBDCCDAADADBACAxABABxBAxDxBBDxBBACDCxxxADCCABCBBADDCCDCxAADCDBACDBAACDDDBDCBADBACAADAxADBDDCDBCCACAAxABBBCCAxACxBCCCAxBBxBDCADAACCCCADxADDBCACCACABDxxCAxDDCBDCADACDADBAxDCCDCDCADBBBxxDBDxDDBAABDCDDBxABAAxBCxAACBCCCxAxAACABABDDBxDCBDCAxABCxDxACxxACCAAADCBDDCBBBCDCDCxCCDCxDCACDCACCxCDxBBCDxACBDBDCxAADADAADDxxxxABBACCBBDACDCBADDCCCBDBCxBBDCCxDAABBADDACBxADDxCDDCDCCDABBxACCAADBDDDxBCCCCDADADABDBxDDDxxADCCCCAABxADCDxDCDAADABCAACCBCCABAABABCDDBADCBxABCBABBxDBCCDCABCxABDDABCACDBDBDBBDxDxxDCDDBCABBBBxDADDAABBDDDCxACCBBBACCAACCCAAxBABBBDACCAACDBDCDACAxCBCDCABCABCBDBxACAABBBDDCxCxxxDCDADDDCBCBBxBACCCxxDACAADBxBCDBAxDCAAxACCDBxBABBADDBBBCBDCBBxBCAACAAAAAADDDBBAADCxCBCBxBCCCACDAADDDABxDDBCBABDADBADCDBCCCDBAAACBxBBxCBBABDAABBBCxxxBDCBCADADBCCDACDxBDCBBBDAADADCDACDCDxADxBDABAxCxDACBABAxABADDxBCCACBCACDAxCBxADABCBxBDADBCDCBDBCACCCCDxBBDxCxxCBABDCBxDCCDBCBACCxABCBACBBxCCDDCxDxCCDBDABBACDDxACCDCBxDDACDCCCDBCDCCBCCDBBBDxDCBBxDAADDCDBCBCBDBDBCABDDDDBxxDAxB"

from collections import Counter


POTIONS_PER_CREATURE = {
    "A": 0,
    "B": 1,
    "C": 3,
    "D": 5,
}


def compute_total_potions(input):
    result = 0
    for i in range(0, len(input), 2):
        if all([val == "x" for val in [input[i], input[i + 1]]]):
            continue

        if "x" in input[i : i + 2]:
            val = input[i + 1] if input[i] == "x" else input[i]
            result += POTIONS_PER_CREATURE[val]
        else:
            val = (
                POTIONS_PER_CREATURE[input[i + 1]] + POTIONS_PER_CREATURE[input[i]] + 2
            )
            result += val
    return result


print(compute_total_potions(TEST_INPUT))

assert compute_total_potions(TEST_INPUT) == 28

print(compute_total_potions(INPUT))
